
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ARQUIVO CARREGAR CHAVEDIR CHAVEESQ CLASSE COLCHETEDIR COLCHETEESQ COM COMANDO COMO CONTAGEM DE DESCRICAO DIFERENTE DIVIDIR DOISPONTOS FILTRAR FUNCAO GRAFICO GRAFICO ID IGUAL JUNTAR MAIORGUAL MAIORQ MAIS MAXIMO MEDIA MENOQ MENORIGUAL MENOS MINIMO NOT NUMDEC NUMINT ONDE OR PARA PARENDIR PARENESQ PIZZA PIZZA PONTO PONTOVIRGULA RECEBE SELECIONE SOMA STRING VEZES VIRGULAprogram : program expression\n               | expressionexpression : CARREGAR STRING COMO IDexpression : MEDIA DE ID PARA IDexpression : SOMA DE ID PARA IDexpression : DESCRICAO DE IDexpression : FILTRAR ID ONDE ID MAIORQ NUMINTexpression : SELECIONE lista_colunas DE IDlista_colunas : lista_colunas VIRGULA ID\n                     | IDexpression : GRAFICO DE ID PARA IDexpression : GRAFICO DE PIZZA DE ID PARA ID VIRGULA ID'
    
_lr_action_items = {'CARREGAR':([0,1,2,10,22,28,32,36,37,39,41,45,],[3,3,-2,-1,-6,-3,-8,-4,-5,-11,-7,-12,]),'MEDIA':([0,1,2,10,22,28,32,36,37,39,41,45,],[4,4,-2,-1,-6,-3,-8,-4,-5,-11,-7,-12,]),'SOMA':([0,1,2,10,22,28,32,36,37,39,41,45,],[5,5,-2,-1,-6,-3,-8,-4,-5,-11,-7,-12,]),'DESCRICAO':([0,1,2,10,22,28,32,36,37,39,41,45,],[6,6,-2,-1,-6,-3,-8,-4,-5,-11,-7,-12,]),'FILTRAR':([0,1,2,10,22,28,32,36,37,39,41,45,],[7,7,-2,-1,-6,-3,-8,-4,-5,-11,-7,-12,]),'SELECIONE':([0,1,2,10,22,28,32,36,37,39,41,45,],[8,8,-2,-1,-6,-3,-8,-4,-5,-11,-7,-12,]),'GRAFICO':([0,1,2,10,22,28,32,36,37,39,41,45,],[9,9,-2,-1,-6,-3,-8,-4,-5,-11,-7,-12,]),'$end':([1,2,10,22,28,32,36,37,39,41,45,],[0,-2,-1,-6,-3,-8,-4,-5,-11,-7,-12,]),'STRING':([3,],[11,]),'DE':([4,5,6,9,16,17,27,33,],[12,13,14,18,24,-10,35,-9,]),'ID':([7,8,12,13,14,18,19,23,24,25,29,30,34,35,42,44,],[15,17,20,21,22,26,28,31,32,33,36,37,39,40,43,45,]),'COMO':([11,],[19,]),'ONDE':([15,],[23,]),'VIRGULA':([16,17,33,43,],[25,-10,-9,44,]),'PIZZA':([18,],[27,]),'PARA':([20,21,26,40,],[29,30,34,42,]),'MAIORQ':([31,],[38,]),'NUMINT':([38,],[41,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'expression':([0,1,],[2,10,]),'lista_colunas':([8,],[16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program expression','program',2,'p_program','analisador.py',148),
  ('program -> expression','program',1,'p_program','analisador.py',149),
  ('expression -> CARREGAR STRING COMO ID','expression',4,'p_comando_carregar','analisador.py',154),
  ('expression -> MEDIA DE ID PARA ID','expression',5,'p_comando_media','analisador.py',163),
  ('expression -> SOMA DE ID PARA ID','expression',5,'p_comando_soma','analisador.py',175),
  ('expression -> DESCRICAO DE ID','expression',3,'p_comando_descricao','analisador.py',187),
  ('expression -> FILTRAR ID ONDE ID MAIORQ NUMINT','expression',6,'p_comando_filtrar','analisador.py',198),
  ('expression -> SELECIONE lista_colunas DE ID','expression',4,'p_comando_selecione_colunas','analisador.py',212),
  ('lista_colunas -> lista_colunas VIRGULA ID','lista_colunas',3,'p_lista_colunas','analisador.py',222),
  ('lista_colunas -> ID','lista_colunas',1,'p_lista_colunas','analisador.py',223),
  ('expression -> GRAFICO DE ID PARA ID','expression',5,'p_comando_grafico','analisador.py',238),
  ('expression -> GRAFICO DE PIZZA DE ID PARA ID VIRGULA ID','expression',9,'p_comando_grafico_pizza','analisador.py',256),
]
